language: java
jdk:
  - openjdk8
branches:
  only:
    - master
before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy #zip에 포함시킬 파일들을 담을 디렉토리
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * #before-deploy 폴더로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy #상위 디렉토리로 이동 후 deploy 폴더 생성
  - mv before-deploy/before-deploy.zip deploy/springboot-webservice.zip #deploy로 zip 파일

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: 2022coala
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: 2022coala
    key: springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true


notifications:
  email:
    recipients:
#    - nakw0410@gmail.com
#    - wlvvwhs@naver.com