language: java
jdk:
- openjdk8
branches:
  only:
  - master
before_install:
   - chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

#before_deploy:
#  - zip -r springboot-webservice ./*
#  - mkdir -p deploy
#  - mv springboot-webservice.zip deploy/springboot-webservice.zip
#
#deploy:
#  - provider: s3
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#
#    bucket: swchoi-springboot-build
#    region: ap-northeast-2
#    skip_cleanup: true
#    acl: private
#    local_dir: deploy
#    wait_until_deployed : true

notifications:
  email:
    recipients:
    - nakw0410@gmail.com
    - wlvvwhs@naver.com