language: java
jdk:
- openjdk8
branches:
  only:
  - master
before_install:
   - chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice ./*
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: 2022coala
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: 2022coala
    key: jaewon-study.zip # S3 버킷에 저장된 jaewon-study.zip 파일을 EC2로 배포
    bundle_type: zip
    application: jaewon-study-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: jaewon-study-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
    - nakw0410@gmail.com